export const QUESTION_BANK: string[] = [
    "Name something you would find in a kitchen",
    "Name a famous movie villain",
    "Name something you take to the beach",
    "Name a fruit that is red",
    "Name something you would find in a classroom",
    "Name a sport played with a ball",
    "Name a famous cartoon character",
    "Name something you would bring on a road trip",
    "Name a type of pizza topping",
    "Name a famous landmark",
    "Name something that comes in pairs",
    "Name a board game",
    "Name a color you would paint a bedroom",
    "Name a country in Europe",
    "Name something you do before bed",
    "Name a type of sandwich",
    "Name a musical instrument",
    "Name a famous band or musician",
    "Name something that makes you sneeze",
    "Name a zoo animal",
    "Name a breakfast food",
    "Name something you would find in a bathroom",
    "Name a holiday",
    "Name a type of shoe",
    "Name something that is cold",
    "Name a TV show everyone has seen",
    "Name a vegetable you would put in a salad",
    "Name a superhero",
    "Name something you would find in a wallet",
    "Name a flavor of ice cream",
    "Name something you would find at a playground",
    "Name a famous book",
    "Name a type of weather",
    "Name something you would find in a hospital",
    "Name a pet that is not a dog or cat",
    "Name something you would find in an office",
    "Name a body of water",
    "Name a famous athlete",
    "Name something round",
    "Name a type of candy",
    "Name something you would do on a snow day",
    "Name a famous painting",
    "Name something that makes noise at night",
    "Name a type of tree",
    "Name something you would find at a gas station",
    "Name a famous historical figure",
    "Name something that is sticky",
    "Name a type of dance",
    "Name something you would find in a hotel room",
    "Name a vegetable that is green",
    "Name a famous video game",
    "Name something you would buy at a farmers market",
    "Name a type of hat",
    "Name something that flies",
    "Name a famous movie quote",
    "Name something you would find in a toolbox",
    "Name a type of pasta",
    "Name something associated with Halloween",
    "Name a famous scientist",
    "Name something you would find at a carnival",
    "Name a word that rhymes with cat",
    "Name an animal that lives in the ocean",
    "Name something you would bring to a picnic",
    "Name a famous Disney movie",
    "Name something you would find in a gym",
    "Name a type of soup",
    "Name something yellow",
    "Name a famous comedian",
    "Name something you would find in a park",
    "Name a type of cheese",
    "Name something associated with Christmas",
    "Name a card game",
    "Name something you would find in a library",
    "Name a type of cookie",
    "Name something that is soft",
    "Name a famous river",
    "Name something you would find at a wedding",
    "Name a type of flower",
    "Name something you would do on a first date",
    "Name a famous president or world leader",
    "Name something you would find in a junk drawer",
    "Name a type of bird",
    "Name something that melts",
    "Name a famous TV character",
    "Name something you would find in a refrigerator",
    "Name a type of car",
    "Name something associated with summer",
    "Name a word that starts with Z",
    "Name a type of dessert that is not ice cream",
    "Name something you would find at an airport",
    "Name a type of fish",
    "Name something that bounces",
    "Name a famous invention",
    "Name something you would find in a purse or bag",
    "Name a type of music genre",
    "Name something that glows",
    "Name a famous fictional detective",
    "Name something you would find at a barbecue",
    "Name a type of berry",
    "Name something you would wish for",
    "Name a famous building",
    "Name something that is blue",
    "Name a type of dog breed",
    "Name something you would find in a tent",
    "Name a country in Asia",
    "Name something associated with birthdays",
    "Name a type of drink that is not water",
    "Name something you would find at a museum",
    "Name a famous fairy tale character",
    "Name something that is sharp",
    "Name a type of nut",
    "Name something you would find at a concert",
    "Name a famous movie from the 90s",
    "Name something you do every morning",
    "Name a type of bean",
    "Name something that is loud",
    "Name a famous love story",
    "Name something you would find on a farm",
    "Name a type of fabric",
    "Name something associated with New Years",
    "Name an animal that starts with the letter B",
    "Name something you would find in space",
    "Name a type of tea",
    "Name something that is scary",
    "Name a famous mountain",
    "Name something you would find at a beach party",
    "Name a word people use when they are excited",
    "Name a type of burger topping",
    "Name something you would never want to step on",
    "Name the best day of the week",
    "Name a place where you have to be quiet",
    "Name something that is overrated",
    "Name a food that is hard to eat neatly",
    "Name the worst household chore",
    "Name a skill everyone should learn",
    "Name a movie you could watch over and over",
    "Name the best snack for a movie night",
    "Name something you always forget",
    "Name the most annoying sound",
    "Name something you would save in a fire",
    "Name an excuse people use for being late",
    "Name something that takes too long",
    "Name the best thing about weekends",
    "Name a food you loved as a kid but not anymore",
    "Name something you do to relax",
    "Name the worst thing to forget on vacation",
    "Name a song everyone knows the words to",
    "Name the most popular app on your phone",
    "Name something you pretend to like",
    "Name the best comfort food",
    "Name something that is always out of stock",
    "Name the most boring sport to watch",
    "Name a smell that everyone likes",
    "Name something you would never do for a million dollars",
    "Name the best thing to dip in chocolate",
    "Name a word people overuse",
    "Name the worst thing to sit next to on a plane",
    "Name an item that is always in the wrong place",
    "Name the most common New Year resolution",
    "Name something that should be illegal but is not",
];
