import type { PokerPlayerView } from "./views";

export const POKER_FIXTURE_IDS = [
    "standard-my-turn",
    "spectator-active-hand",
    "backwards-visible-opponents",
    "tournament-over-host",
] as const;

export type PokerFixtureId = (typeof POKER_FIXTURE_IDS)[number];

export interface PokerFixture {
    id: PokerFixtureId;
    roomId: string;
    title: string;
    hostPlayerId: string;
    primaryPlayerId: string;
    description: string;
    view: PokerPlayerView;
}

const POKER_FIXTURES: Record<PokerFixtureId, PokerFixture> = {
    "standard-my-turn": {
        id: "standard-my-turn",
        roomId: "fixture-poker-standard",
        title: "Texas Hold'em",
        hostPlayerId: "p1",
        primaryPlayerId: "p1",
        description: "Seated player is facing a live turn with exposed board state.",
        view: {
            myHoleCards: [
                { rank: 1, suit: "spade" },
                { rank: 13, suit: "heart" },
            ],
            myHoleCardCount: 2,
            myStack: 980,
            myStatus: "active",
            isSpectator: false,
            legalActions: ["fold", "call", "raise", "all_in"],
            callAmount: 40,
            minBetOrRaise: 100,
            maxBet: 980,
            players: [
                {
                    id: "p1",
                    name: "Alice",
                    stack: 980,
                    status: "active",
                    connected: true,
                    committedThisStreet: 20,
                    committedThisHand: 140,
                    holeCardCount: 2,
                    visibleHoleCards: [],
                    isDealer: false,
                    isSmallBlind: true,
                    isBigBlind: false,
                    isActing: true,
                },
                {
                    id: "p2",
                    name: "Bob",
                    stack: 820,
                    status: "active",
                    connected: true,
                    committedThisStreet: 40,
                    committedThisHand: 140,
                    holeCardCount: 2,
                    visibleHoleCards: [],
                    isDealer: false,
                    isSmallBlind: false,
                    isBigBlind: true,
                    isActing: false,
                },
                {
                    id: "p3",
                    name: "Cara",
                    stack: 1160,
                    status: "active",
                    connected: true,
                    committedThisStreet: 40,
                    committedThisHand: 140,
                    holeCardCount: 2,
                    visibleHoleCards: [],
                    isDealer: true,
                    isSmallBlind: false,
                    isBigBlind: false,
                    isActing: false,
                },
            ],
            board: [
                { rank: 12, suit: "club" },
                { rank: 11, suit: "diamond" },
                { rank: 10, suit: "spade" },
                { rank: 2, suit: "heart" },
            ],
            pots: [
                {
                    amount: 420,
                    eligiblePlayerIds: ["p1", "p2", "p3"],
                },
            ],
            actingPlayerId: "p1",
            street: "turn",
            handNumber: 7,
            eventLog: [
                {
                    id: 18,
                    type: "board_dealt",
                    message: "Turn dealt",
                    street: "turn",
                },
                {
                    id: 19,
                    type: "player_action",
                    message: "Bob bet 40",
                    playerId: "p2",
                    amount: 40,
                    street: "turn",
                },
            ],
            spectators: [],
            endedByHost: false,
            winnerIds: null,
        },
    },
    "spectator-active-hand": {
        id: "spectator-active-hand",
        roomId: "fixture-poker-spectator",
        title: "Texas Hold'em",
        hostPlayerId: "p1",
        primaryPlayerId: "p4",
        description: "Late joiner is spectating an active hand.",
        view: {
            myHoleCards: [],
            myHoleCardCount: 0,
            myStack: 0,
            myStatus: "spectator",
            isSpectator: true,
            legalActions: [],
            callAmount: 0,
            minBetOrRaise: null,
            maxBet: 0,
            players: [
                {
                    id: "p1",
                    name: "Alice",
                    stack: 920,
                    status: "active",
                    connected: true,
                    committedThisStreet: 20,
                    committedThisHand: 80,
                    holeCardCount: 2,
                    visibleHoleCards: [],
                    isDealer: false,
                    isSmallBlind: false,
                    isBigBlind: true,
                    isActing: false,
                },
                {
                    id: "p2",
                    name: "Bob",
                    stack: 1040,
                    status: "active",
                    connected: true,
                    committedThisStreet: 20,
                    committedThisHand: 80,
                    holeCardCount: 2,
                    visibleHoleCards: [],
                    isDealer: true,
                    isSmallBlind: true,
                    isBigBlind: false,
                    isActing: true,
                },
                {
                    id: "p3",
                    name: "Cara",
                    stack: 1040,
                    status: "folded",
                    connected: true,
                    committedThisStreet: 0,
                    committedThisHand: 80,
                    holeCardCount: 2,
                    visibleHoleCards: [],
                    isDealer: false,
                    isSmallBlind: false,
                    isBigBlind: false,
                    isActing: false,
                },
            ],
            board: [
                { rank: 4, suit: "spade" },
                { rank: 4, suit: "club" },
                { rank: 9, suit: "heart" },
            ],
            pots: [
                {
                    amount: 240,
                    eligiblePlayerIds: ["p1", "p2"],
                },
            ],
            actingPlayerId: "p2",
            street: "flop",
            handNumber: 3,
            eventLog: [
                {
                    id: 9,
                    type: "player_action",
                    message: "Cara folded",
                    playerId: "p3",
                    street: "flop",
                },
            ],
            spectators: [{ id: "p4", name: "Dana" }],
            endedByHost: false,
            winnerIds: null,
        },
    },
    "backwards-visible-opponents": {
        id: "backwards-visible-opponents",
        roomId: "fixture-poker-backwards",
        title: "Backwards Poker",
        hostPlayerId: "p1",
        primaryPlayerId: "p1",
        description: "Seated player sees opponents' cards instead of their own.",
        view: {
            myHoleCards: [],
            myHoleCardCount: 2,
            myStack: 960,
            myStatus: "active",
            isSpectator: false,
            legalActions: ["fold", "call", "all_in"],
            callAmount: 20,
            minBetOrRaise: null,
            maxBet: 960,
            players: [
                {
                    id: "p1",
                    name: "Alice",
                    stack: 960,
                    status: "active",
                    connected: true,
                    committedThisStreet: 20,
                    committedThisHand: 20,
                    holeCardCount: 2,
                    visibleHoleCards: [],
                    isDealer: false,
                    isSmallBlind: false,
                    isBigBlind: true,
                    isActing: true,
                },
                {
                    id: "p2",
                    name: "Bob",
                    stack: 990,
                    status: "active",
                    connected: true,
                    committedThisStreet: 10,
                    committedThisHand: 10,
                    holeCardCount: 2,
                    visibleHoleCards: [
                        { rank: 12, suit: "heart" },
                        { rank: 12, suit: "diamond" },
                    ],
                    isDealer: true,
                    isSmallBlind: true,
                    isBigBlind: false,
                    isActing: false,
                },
                {
                    id: "p3",
                    name: "Cara",
                    stack: 1000,
                    status: "active",
                    connected: true,
                    committedThisStreet: 20,
                    committedThisHand: 20,
                    holeCardCount: 2,
                    visibleHoleCards: [
                        { rank: 1, suit: "club" },
                        { rank: 10, suit: "club" },
                    ],
                    isDealer: false,
                    isSmallBlind: false,
                    isBigBlind: false,
                    isActing: false,
                },
            ],
            board: [],
            pots: [
                {
                    amount: 50,
                    eligiblePlayerIds: ["p1", "p2", "p3"],
                },
            ],
            actingPlayerId: "p1",
            street: "preflop",
            handNumber: 2,
            eventLog: [
                {
                    id: 3,
                    type: "hand_started",
                    message: "Hand 2 started",
                    street: "preflop",
                },
            ],
            spectators: [],
            endedByHost: false,
            winnerIds: null,
        },
    },
    "tournament-over-host": {
        id: "tournament-over-host",
        roomId: "fixture-poker-results",
        title: "Texas Hold'em",
        hostPlayerId: "p1",
        primaryPlayerId: "p1",
        description: "Host is viewing the final standings overlay.",
        view: {
            myHoleCards: [],
            myHoleCardCount: 0,
            myStack: 1840,
            myStatus: "active",
            isSpectator: false,
            legalActions: [],
            callAmount: 0,
            minBetOrRaise: null,
            maxBet: 0,
            players: [
                {
                    id: "p1",
                    name: "Alice",
                    stack: 1840,
                    status: "active",
                    connected: true,
                    committedThisStreet: 0,
                    committedThisHand: 0,
                    holeCardCount: 0,
                    visibleHoleCards: [],
                    isDealer: false,
                    isSmallBlind: false,
                    isBigBlind: false,
                    isActing: false,
                },
                {
                    id: "p2",
                    name: "Bob",
                    stack: 1160,
                    status: "busted",
                    connected: true,
                    committedThisStreet: 0,
                    committedThisHand: 0,
                    holeCardCount: 0,
                    visibleHoleCards: [],
                    isDealer: false,
                    isSmallBlind: false,
                    isBigBlind: false,
                    isActing: false,
                },
                {
                    id: "p3",
                    name: "Cara",
                    stack: 0,
                    status: "busted",
                    connected: false,
                    committedThisStreet: 0,
                    committedThisHand: 0,
                    holeCardCount: 0,
                    visibleHoleCards: [],
                    isDealer: false,
                    isSmallBlind: false,
                    isBigBlind: false,
                    isActing: false,
                },
            ],
            board: [
                { rank: 8, suit: "spade" },
                { rank: 8, suit: "diamond" },
                { rank: 3, suit: "club" },
                { rank: 3, suit: "heart" },
                { rank: 1, suit: "heart" },
            ],
            pots: [],
            actingPlayerId: null,
            street: "tournament_over",
            handNumber: 11,
            eventLog: [
                {
                    id: 41,
                    type: "showdown",
                    message: "Alice showed Full House",
                    street: "showdown",
                },
                {
                    id: 42,
                    type: "pot_awarded",
                    message: "Alice won 620 chips with Full House",
                    amount: 620,
                    street: "showdown",
                },
            ],
            spectators: [],
            endedByHost: false,
            winnerIds: ["p1"],
        },
    },
};

const FIXTURE_PLAYER_IDS = ["p1", "p2", "p3", "p4"] as const;

export function getPokerFixture(fixtureId: PokerFixtureId) {
    return POKER_FIXTURES[fixtureId];
}

export function getDefaultFixturePlayerId(fixtureId: PokerFixtureId) {
    return POKER_FIXTURES[fixtureId].primaryPlayerId;
}

export function getFixturePlayerIds(): string[] {
    return [...FIXTURE_PLAYER_IDS];
}
