/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizNewRouteImport } from './routes/quiz/new'
import { Route as QuizQuizIdRouteImport } from './routes/quiz/$quizId'
import { Route as QuizQuizIdQuestionNewRouteImport } from './routes/quiz/$quizId/question/new'
import { Route as QuizQuizIdQuestionQuestionIdRouteImport } from './routes/quiz/$quizId/question/$questionId'

const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizNewRoute = QuizNewRouteImport.update({
  id: '/quiz/new',
  path: '/quiz/new',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizQuizIdRoute = QuizQuizIdRouteImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizQuizIdQuestionNewRoute = QuizQuizIdQuestionNewRouteImport.update({
  id: '/question/new',
  path: '/question/new',
  getParentRoute: () => QuizQuizIdRoute,
} as any)
const QuizQuizIdQuestionQuestionIdRoute =
  QuizQuizIdQuestionQuestionIdRouteImport.update({
    id: '/question/$questionId',
    path: '/question/$questionId',
    getParentRoute: () => QuizQuizIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tags': typeof TagsRoute
  '/quiz/$quizId': typeof QuizQuizIdRouteWithChildren
  '/quiz/new': typeof QuizNewRoute
  '/quiz/$quizId/question/$questionId': typeof QuizQuizIdQuestionQuestionIdRoute
  '/quiz/$quizId/question/new': typeof QuizQuizIdQuestionNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tags': typeof TagsRoute
  '/quiz/$quizId': typeof QuizQuizIdRouteWithChildren
  '/quiz/new': typeof QuizNewRoute
  '/quiz/$quizId/question/$questionId': typeof QuizQuizIdQuestionQuestionIdRoute
  '/quiz/$quizId/question/new': typeof QuizQuizIdQuestionNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tags': typeof TagsRoute
  '/quiz/$quizId': typeof QuizQuizIdRouteWithChildren
  '/quiz/new': typeof QuizNewRoute
  '/quiz/$quizId/question/$questionId': typeof QuizQuizIdQuestionQuestionIdRoute
  '/quiz/$quizId/question/new': typeof QuizQuizIdQuestionNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/tags'
    | '/quiz/$quizId'
    | '/quiz/new'
    | '/quiz/$quizId/question/$questionId'
    | '/quiz/$quizId/question/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/tags'
    | '/quiz/$quizId'
    | '/quiz/new'
    | '/quiz/$quizId/question/$questionId'
    | '/quiz/$quizId/question/new'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/tags'
    | '/quiz/$quizId'
    | '/quiz/new'
    | '/quiz/$quizId/question/$questionId'
    | '/quiz/$quizId/question/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  TagsRoute: typeof TagsRoute
  QuizQuizIdRoute: typeof QuizQuizIdRouteWithChildren
  QuizNewRoute: typeof QuizNewRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/new': {
      id: '/quiz/new'
      path: '/quiz/new'
      fullPath: '/quiz/new'
      preLoaderRoute: typeof QuizNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$quizId': {
      id: '/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/quiz/$quizId'
      preLoaderRoute: typeof QuizQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$quizId/question/new': {
      id: '/quiz/$quizId/question/new'
      path: '/question/new'
      fullPath: '/quiz/$quizId/question/new'
      preLoaderRoute: typeof QuizQuizIdQuestionNewRouteImport
      parentRoute: typeof QuizQuizIdRoute
    }
    '/quiz/$quizId/question/$questionId': {
      id: '/quiz/$quizId/question/$questionId'
      path: '/question/$questionId'
      fullPath: '/quiz/$quizId/question/$questionId'
      preLoaderRoute: typeof QuizQuizIdQuestionQuestionIdRouteImport
      parentRoute: typeof QuizQuizIdRoute
    }
  }
}

interface QuizQuizIdRouteChildren {
  QuizQuizIdQuestionQuestionIdRoute: typeof QuizQuizIdQuestionQuestionIdRoute
  QuizQuizIdQuestionNewRoute: typeof QuizQuizIdQuestionNewRoute
}

const QuizQuizIdRouteChildren: QuizQuizIdRouteChildren = {
  QuizQuizIdQuestionQuestionIdRoute: QuizQuizIdQuestionQuestionIdRoute,
  QuizQuizIdQuestionNewRoute: QuizQuizIdQuestionNewRoute,
}

const QuizQuizIdRouteWithChildren = QuizQuizIdRoute._addFileChildren(
  QuizQuizIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  TagsRoute: TagsRoute,
  QuizQuizIdRoute: QuizQuizIdRouteWithChildren,
  QuizNewRoute: QuizNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
