/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomIndexRouteImport } from './routes/room/index'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as RoomRoomIdIndexRouteImport } from './routes/room/$roomId/index'
import { Route as ApiUsersUserIdRouteImport } from './routes/api/users.$userId'
import { Route as ApiRoomRoomIdRouteImport } from './routes/api/room/$roomId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomIndexRoute = RoomIndexRouteImport.update({
  id: '/room/',
  path: '/room/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdIndexRoute = RoomRoomIdIndexRouteImport.update({
  id: '/room/$roomId/',
  path: '/room/$roomId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersUserIdRoute = ApiUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ApiUsersRoute,
} as any)
const ApiRoomRoomIdRoute = ApiRoomRoomIdRouteImport.update({
  id: '/api/room/$roomId',
  path: '/api/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/room': typeof RoomIndexRoute
  '/api/room/$roomId': typeof ApiRoomRoomIdRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/room/$roomId': typeof RoomRoomIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/room': typeof RoomIndexRoute
  '/api/room/$roomId': typeof ApiRoomRoomIdRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/room/$roomId': typeof RoomRoomIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/room/': typeof RoomIndexRoute
  '/api/room/$roomId': typeof ApiRoomRoomIdRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/room/$roomId/': typeof RoomRoomIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/users'
    | '/room'
    | '/api/room/$roomId'
    | '/api/users/$userId'
    | '/room/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/users'
    | '/room'
    | '/api/room/$roomId'
    | '/api/users/$userId'
    | '/room/$roomId'
  id:
    | '__root__'
    | '/'
    | '/api/users'
    | '/room/'
    | '/api/room/$roomId'
    | '/api/users/$userId'
    | '/room/$roomId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
  RoomIndexRoute: typeof RoomIndexRoute
  ApiRoomRoomIdRoute: typeof ApiRoomRoomIdRoute
  RoomRoomIdIndexRoute: typeof RoomRoomIdIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/': {
      id: '/room/'
      path: '/room'
      fullPath: '/room'
      preLoaderRoute: typeof RoomIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId/': {
      id: '/room/$roomId/'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/$userId': {
      id: '/api/users/$userId'
      path: '/$userId'
      fullPath: '/api/users/$userId'
      preLoaderRoute: typeof ApiUsersUserIdRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/api/room/$roomId': {
      id: '/api/room/$roomId'
      path: '/api/room/$roomId'
      fullPath: '/api/room/$roomId'
      preLoaderRoute: typeof ApiRoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiUsersRouteChildren {
  ApiUsersUserIdRoute: typeof ApiUsersUserIdRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersUserIdRoute: ApiUsersUserIdRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiUsersRoute: ApiUsersRouteWithChildren,
  RoomIndexRoute: RoomIndexRoute,
  ApiRoomRoomIdRoute: ApiRoomRoomIdRoute,
  RoomRoomIdIndexRoute: RoomRoomIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
