/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevIndexRouteImport } from './routes/dev/index'
import { Route as DevGameRouteImport } from './routes/dev/$game'
import { Route as DevAssetRouteImport } from './routes/dev/asset'
import { Route as RoomIndexRouteImport } from './routes/room/index'
import { Route as RoomRoomIdIndexRouteImport } from './routes/room/$roomId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevIndexRoute = DevIndexRouteImport.update({
  id: '/dev/',
  path: '/dev/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevGameRoute = DevGameRouteImport.update({
  id: '/dev/$game',
  path: '/dev/$game',
  getParentRoute: () => rootRouteImport,
} as any)
const DevAssetRoute = DevAssetRouteImport.update({
  id: '/dev/asset',
  path: '/dev/asset',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomIndexRoute = RoomIndexRouteImport.update({
  id: '/room/',
  path: '/room/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdIndexRoute = RoomRoomIdIndexRouteImport.update({
  id: '/room/$roomId/',
  path: '/room/$roomId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev/$game': typeof DevGameRoute
  '/dev/asset': typeof DevAssetRoute
  '/dev/': typeof DevIndexRoute
  '/room/': typeof RoomIndexRoute
  '/room/$roomId/': typeof RoomRoomIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev/$game': typeof DevGameRoute
  '/dev/asset': typeof DevAssetRoute
  '/dev': typeof DevIndexRoute
  '/room': typeof RoomIndexRoute
  '/room/$roomId': typeof RoomRoomIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev/$game': typeof DevGameRoute
  '/dev/asset': typeof DevAssetRoute
  '/dev/': typeof DevIndexRoute
  '/room/': typeof RoomIndexRoute
  '/room/$roomId/': typeof RoomRoomIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/dev/$game' | '/dev/asset' | '/dev/' | '/room/' | '/room/$roomId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dev/$game' | '/dev/asset' | '/dev' | '/room' | '/room/$roomId'
  id:
    | '__root__'
    | '/'
    | '/dev/$game'
    | '/dev/asset'
    | '/dev/'
    | '/room/'
    | '/room/$roomId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevGameRoute: typeof DevGameRoute
  DevAssetRoute: typeof DevAssetRoute
  DevIndexRoute: typeof DevIndexRoute
  RoomIndexRoute: typeof RoomIndexRoute
  RoomRoomIdIndexRoute: typeof RoomRoomIdIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/': {
      id: '/dev/'
      path: '/dev'
      fullPath: '/dev/'
      preLoaderRoute: typeof DevIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/$game': {
      id: '/dev/$game'
      path: '/dev/$game'
      fullPath: '/dev/$game'
      preLoaderRoute: typeof DevGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/asset': {
      id: '/dev/asset'
      path: '/dev/asset'
      fullPath: '/dev/asset'
      preLoaderRoute: typeof DevAssetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/': {
      id: '/room/'
      path: '/room'
      fullPath: '/room/'
      preLoaderRoute: typeof RoomIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId/': {
      id: '/room/$roomId/'
      path: '/room/$roomId'
      fullPath: '/room/$roomId/'
      preLoaderRoute: typeof RoomRoomIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevGameRoute: DevGameRoute,
  DevAssetRoute: DevAssetRoute,
  DevIndexRoute: DevIndexRoute,
  RoomIndexRoute: RoomIndexRoute,
  RoomRoomIdIndexRoute: RoomRoomIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
