export const QUESTION_BANK: string[] = [
    "How many hours of sleep do you need to feel rested?",
    "How many countries have you visited?",
    "How many years of your life would you give up to become a billionaire instantly?",
    "How long is the perfect nap (in minutes)?",
    "How many times a day do you check your phone?",
    "On a scale of 1 to 10, how good of a cook are you?",
    "How many books did you read last year?",
    "What's the latest you'd sleep in on a weekend? (hour, e.g. 8, 9, 10)",
    "How many close friends do you have?",
    "How many minutes does it take you to get ready in the morning?",
    "How many pets have you had in your lifetime?",
    "On a scale of 1 to 10, how adventurous are you?",
    "How many times a week do you exercise?",
    "How many hours a day do you spend on social media?",
    "How many siblings do you have?",
    "How many concerts have you been to?",
    "On a scale of 1 to 10, how good is your sense of direction?",
    "How many cups of coffee or tea do you drink per day?",
    "How many languages do you speak (even a little)?",
    "How many times have you moved homes in your life?",
    "How old were you when you had your first kiss?",
    "How many pairs of shoes do you own?",
    "On a scale of 1 to 10, how patient are you?",
    "How many hours a week do you spend cooking?",
    "How many tattoos do you have?",
    "How many different jobs have you had?",
    "How many hours of TV do you watch per day?",
    "On a scale of 1 to 10, how much do you like spicy food?",
    "How many unread emails are in your inbox right now?",
    "How many weddings have you attended?",
    "How old were you when you got your first phone?",
    "How many times a year do you go to the movies?",
    "On a scale of 1 to 10, how good are you at keeping secrets?",
    "How many plants do you have at home?",
    "How many minutes would you wait in line for your favorite restaurant?",
    "How many alarms do you set in the morning?",
    "On a scale of 1 to 10, how competitive are you?",
    "How many times have you been on an airplane?",
    "How many hours a day do you listen to music?",
    "How old were you when you learned to ride a bike?",
    "How many photos are on your phone right now (in hundreds)?",
    "How many minutes does your ideal shower last?",
    "On a scale of 1 to 10, how much of a morning person are you?",
    "How many streaming services do you subscribe to?",
    "How many hours could you survive without your phone?",
    "How many times have you been to a theme park?",
    "On a scale of 1 to 10, how good is your handwriting?",
    "How many different cities have you lived in?",
    "How many minutes early do you typically arrive to things?",
    "How many love stories has your grandma really had?",
];
